In [13]:
"""**Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
"""

import numpy as np

# Задание 1
a = np.arange(12,24)

# Задание 2
a1=a.reshape(2, 6)
a2=a.reshape(3, 4)
a3=a.reshape(6, 2)
a4=a.reshape(4, 3)
a5=a.reshape(12, 1)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [22]:
"""
3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
(в трех примерах - для обозначения числа столбцов, в двух - для строк).
"""

n1=a.reshape(2, -1)
n2=a.reshape(3, -1)
n3=a.reshape(-1, 2)
n4=a.reshape(-1, 3)
n5=a.reshape(12, -1)

print(n1)
print(n2)
print(n3)
print(n4)
print(n5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [40]:
"""
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
"""
# Для проверки этого условия создадим вектор Х 
x = np.arange(1,13)

# На втором этапе мы развернем его по вертикали
y = x.reshape(12,1)

# На третьем развернем обратно по горизонтали
z = y.reshape(1,12)
x,y,z

print('Вектор:', x)
print("Первое колдовство:", y)
print("Попытка вернуть как было:", z)

print('*' * 50)

# Что мы видим - если на начальном этапе массив был одномерным, то после колдовства - он превратился в двумерный 
# (еще на первом этапе магии). 
# А именно двумерным массивом с одним столбцом и строками внутри. Это видно по дополнительным []. 
# Также это можно проверить индексами, которые становятся двумерными и требуют двумерный индекс

print ("Векторный индекс [0]:", x[0])
print ("Тот же индекс два раза перевернутого вектора [0]:", z[0])
print ("Использование двойных индексов [0][0], чтобы получить значение из п.1:", z[0][0])

Вектор: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Первое колдовство: [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Попытка вернуть как было: [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
**************************************************
Векторный индекс [0]: 1
Тот же индекс два раза перевернутого вектора [0]: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Использование двойных индексов [0][0], чтобы получить значение из п.1: 1


In [54]:
"""
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из 
нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

"""

g=np.random.randn(3,4)
print("\n Исходный массив из задания: \n",g)

b=g.flatten()
print("\n Векторный массив из задания: \n",b)

if b.size == g.size:
    print('\n Их размеры равны')
else:
    print('Размеры массивов разные, нужно искать ошибку')



 Исходный массив из задания: 
 [[ 0.95866019 -1.59251797 -1.91367062  0.45788119]
 [-0.62723937  0.2815126   0.88196185  2.8411409 ]
 [-0.06340771  0.05402375 -0.46991488  1.34393671]]

 Векторный массив из задания: 
 [ 0.95866019 -1.59251797 -1.91367062  0.45788119 -0.62723937  0.2815126
  0.88196185  2.8411409  -0.06340771  0.05402375 -0.46991488  1.34393671]

 Их размеры равны


In [58]:
"""
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
"""

a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [67]:
"""
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 
невключительно с интервалом 2. В чем разница между массивами a и b?

"""

b = np.arange(20,1,-2).reshape(1,10)
b

# Главное отличие - это то, что массив а - одномерный (нет строк, только "столбцы"), 
# а массив b - двумерный (как минимум 1 строка). 



array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [91]:
"""Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого 
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. 
Итоговый массив v должен иметь атрибут size, равный 10.
"""

a = np.zeros((2,2))

print('Zeros a: \n', a)

b = np.ones((3,2))
print('Ones b: \n', b)

v = np.vstack((a, b))
print('Collab v: \n',v)

print('\n', '*' * 50)
print('\nV size: ',v.size)

Zeros a: 
 [[0. 0.]
 [0. 0.]]
Ones b: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Collab v: 
 [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 **************************************************

V size:  10


In [144]:
"""Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
""" 

a = np.arange(0,12).reshape(4,3)
print('Array a - DONE! \n',a)

at = a.transpose()

print('\nArray At - DONE (transposed)! \n',at)

b = np.dot(a, at)
print('\nArrays a and At were multiplied! \n',b,'\nSize of the result is:',b.size,'\nShape of the result is:',b.shape)

# Что бы это ни было, но не получается по причине сингулярности матрицы. Читаю про про вырождение матриц. Шокирован.
# b_inv=np.linalg.inv(b)
# b_inv

Array a - DONE! 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Array At - DONE (transposed)! 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

Arrays a and At were multiplied! 
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 
Size of the result is: 16 
Shape of the result is: (4, 4)


In [112]:
"""Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42."""

np.random.seed(42)

In [177]:
"""
1. Создайте одномерный массив c, составленный из последовательности 16-ти случайных 
равномерно распределенных целых чисел от 0 до 16 невключительно. 

2. Поменяйте его форму так, чтобы получилась квадратная матрица C. 

3. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 

4. Вычислите определитель, ранг и обратную матрицу D_inv для D.

"""
from math import sqrt

c = np.random.randint(0, 16,16)

c_calc = int(sqrt(c.size)) # Автоматическое создание квадратных матриц (если это возможно и при идеальном пользователе)

C = c.reshape(c_calc,c_calc)

D = (b + (np.dot(C,10))) # b взята из предыдущего задания. Матрица С умножается на скаляр

d_opr = np.linalg.det(D)
d_rang = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)

print(f'Определитель D: {d_opr}\nРанг D: {d_rang}\nОбратная матрица D: \n{D_inv}\n')

Определитель D: 47538400.000000104
Ранг D: 4
Обратная матрица D: 
[[ 0.01305723 -0.01354442  0.02806994 -0.02104909]
 [ 0.02873382 -0.02633576  0.02789408 -0.01841122]
 [ 0.02602359 -0.00409858  0.00048634 -0.00729516]
 [-0.03919779  0.02176935 -0.02148074  0.0222111 ]]



In [178]:
"""
5. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы. 

6. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C."""

D_inv = np.where(D_inv<=0, 0, 1)

print('D_inv с 0 и 1 на отрицательных и положительных значений:\n',D_inv,'\n')


E = np.where(D_inv == 1, b, C)

print('Матрица Е с подстановкой значений из матриц В и С по маске:\n',E)

D_inv с 0 и 1 на отрицательных и положительных значений:
 [[1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 0 1]] 

Матрица Е с подстановкой значений из матриц В и С по маске:
 [[  5   6  23  10]
 [ 14   1  86  11]
 [ 23   9 149  11]
 [  0 122   5 302]]
